services:
  catalog-service:
    depends_on:
      - polar-postgres
    image: "catalog-service"
    container_name: "catalog-service"
    ports:
      - 9001:9001
    environment:
      BPL_JVM_THREAD_COUNT: 50
      SPRING_DATASOURCE_URL: "jdbc:postgresql://${services.polar-postgres.container_name}:5432/polardb_catalog"
      SPRING_PROFILES_ACTIVE: "testdata"

  polar-postgres:
    image: "postgres:14.4-alpine"
    container_name: "polar-postgres"
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "polardb_catalog"