services:
  catalog-service:
    depends_on:
      polar-postgres:
        condition: service_healthy
        restart: true
      config-service:
        condition: service_healthy
        restart: true
    image: catalog-service
    container_name: catalog-service
    ports:
      - 9001:9001
      - 8001:8001
    environment:
      BPL_JVM_THREAD_COUNT: 50
      BPL_DEBUG_ENABLED: true
      BPL_DEBUG_PORT: 8001
      SPRING_CLOUD_CONFIG_URI: http://config-service:8888
      SPRING_DATASOURCE_URL: jdbc:postgresql://polar-postgres:5432/polardb_catalog
      SPRING_PROFILES_ACTIVE: testdata

  order-service:
    depends_on:
      polar-postgres:
        condition: service_healthy
        restart: true
      config-service:
        condition: service_healthy
        restart: true
    image: order-service
    container_name: order-service
    ports:
      - 9002:9002
      - 8002:8002
    environment:
      BPL_DEBUG_ENABLED: true
      BPL_DEBUG_PORT: 8002
      POLAR_CATALOG_SERVICE_URI: http://catalog-service:9001
      SPRING_CLOUD_CONFIG_URI: http://config-service:8888
      SPRING_R2DBC_URL: r2dbc:postgresql://polar-postgres:5432/polardb_order
      SPRING_FLYWAY_URL: jdbc:postgresql://polar-postgres:5432/polardb_order

  config-service:
    image: config-service
    container_name: config-service
    command: >
      sh -c "apt install -y curl"
    ports:
      - 8888:8888
      - 9888:9888
    environment:
      BPL_THREAD_COUNT: 50
      BPL_DEBUG_ENABLED: true
      BPL_DEBUG_PORT: 9888
      THC_PORT: 8888
      THC_PATH: actuator/health
    healthcheck:
      test: ./health-check
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 3s
  
  edge-service:
    depends_on:
      polar-redis:
        condition: service_healthy
    image: edge-service
    container_name: edge-service
    ports:
      - 9000:9000
      - 10000:10000
    environment:
      BPL_DEBUG_ENABLED: true
      BPL_DEBUG_PORT: 10000
      CATALOG_SERVICE_URL: http://catalog-service:9001
      ORDER_SERVICE_URL: http://order-service:9002
      SPRING_CLOUD_CONFIG_URI: http://config-service:8888
      SPRING_DATA_REDIS_HOST: polar-redis

  polar-postgres:
    image: postgres:14.4-alpine
    container_name: polar-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  
  polar-redis:
    image: redis:7.4-alpine
    container_name: polar-redis
    ports:
      - 6379:6379
    healthcheck:
      test: redis-cli ping
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 3s